fix: set required `value` on `@Generated`
This fixes compilation error:
No explicit/default value found for annotation attribute
'value' in @jakarta.annotation.Generated